[versions]
kotlin = "2.3.21"
ksp = "2.3.9"
kotlinCompileTesting = "0.12.1"
junit = "5.14.3"
hamcrest = "3.0"

[libraries]

ksp-symbol-processing-api = {group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlin-compile-testing = {group = "dev.zacsweers.kctfork", name = "core", version.ref = "kotlinCompileTesting" }
kotlin-compile-testing-ksp = {group = "dev.zacsweers.kctfork", name = "ksp", version.ref = "kotlinCompileTesting" }
kotlin-test-junit5 = {group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
junit-jupiter-api = {group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = {group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-jupiter-engine = {group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
hamcrest = {group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }

[plugins]
kotlin =  { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
