{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gershnik",
    "module": "smjni-jnigen-kprocessor",
    "version": "3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "mqxrclr67bghtappkgu3hrcs3y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "smjni-jnigen-kprocessor-3.5.jar",
          "url": "smjni-jnigen-kprocessor-3.5.jar",
          "size": 109914,
          "sha512": "c99a8a4eb8b746a192d3cc52cf17fa72eedcddfb19216bc34cb899b9974732fcfb1f8886e91c8268a747b14acb2393b5eb6c172a8c4cb05c8f96876d523fb6ec",
          "sha256": "73eb11226c8b432ef2a53828a4f61779171501c9bb58eb17bf095c1c3f089f5c",
          "sha1": "ecaca06b8a36dd78f11f4219f4f3ace7bda9dcba",
          "md5": "61b04012db12efe12ad33d98ac94d028"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.5.31-1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "smjni-jnigen-kprocessor-3.5.jar",
          "url": "smjni-jnigen-kprocessor-3.5.jar",
          "size": 109914,
          "sha512": "c99a8a4eb8b746a192d3cc52cf17fa72eedcddfb19216bc34cb899b9974732fcfb1f8886e91c8268a747b14acb2393b5eb6c172a8c4cb05c8f96876d523fb6ec",
          "sha256": "73eb11226c8b432ef2a53828a4f61779171501c9bb58eb17bf095c1c3f089f5c",
          "sha1": "ecaca06b8a36dd78f11f4219f4f3ace7bda9dcba",
          "md5": "61b04012db12efe12ad33d98ac94d028"
        }
      ]
    }
  ]
}
