name: Publish

on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Release Name
        shell: python
        run: |
          import os
          #ref = os.environ['GITHUB_REF']
          #name = ref[ref.rfind('/') + 1:]
          with open('VERSION', 'r') as verFile:
            name = verFile.read().strip()
          with open(os.environ['GITHUB_ENV'], 'w') as env:
            print('RELEASE_NAME=' + name, file=env)

      - name: Bundle Code
        working-directory: ${{github.workspace}}/jnigen
        shell: bash
        run: ./gradlew -PbuildDir=build bundleCpp bundleJava

      - name: Publish to OSSRH
        working-directory: ${{github.workspace}}/jnigen
        shell: bash
        run: |
          ./gradlew -PbuildDir=build \
              -Psigning.keyId=${{ secrets.GPG_KEY_ID }} \
              -Psigning.password=${{ secrets.GPG_KEY_PASSWD }} \
              -Psigning.armoredKey=${{ secrets.GPG_KEY }} \
              -PossrhUsername=${{ secrets.OSSRH_USERNAME }} \
              -PossrhPassword=${{ secrets.OSSRH_PASSWORD }} \
            publishAllPublicationsToOssrhRepository

      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          name: ${{ env.RELEASE_NAME }}
          body: ...edit me...
          files: |
            jnigen/build/SimpleJNI-${{ env.RELEASE_NAME }}-cpp-only.zip
            jnigen/build/SimpleJNI-${{ env.RELEASE_NAME }}-jnigen.zip